<?php

declare(strict_types=1);

namespace Tolyan\Openai\ChatCompletion\Message\Assistant;

final readonly class UnknownFunctionCall implements ToolCallInterface
{
    public ToolCallTypeEnum $type;

    /**
     * @param string $id        the ID of the tool call
     * @param string $name      the name of the function to call
     * @param string $arguments The arguments to call the function with,
     *                          as generated by the model in JSON format.
     *                          Note that the model does not always generate valid JSON,
     *                          and may hallucinate parameters not defined by your function schema.
     *                          Validate the arguments in your code before calling your function.
     */
    public function __construct(
        public string $id,
        public string $name,
        public string $arguments,
    ) {
        $this->type = ToolCallTypeEnum::FUNCTION;
    }
}